name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  #
  # We only build the java artifacts during pull request, because building the
  # full docker image takes much longer. That is only run after code has been
  # merged or as part of a release.
  #
  buildandtest:
    name: Assemble and test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.212'
      - name: Build and test
        run: ./gradlew assemble test integrationTest
  style:
    name: Check code style
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.212'
      - name: Check style
        run: ./gradlew style
